
interface _GlobalComponents {
      'MfpPopup': typeof import("../components/MfpPopup.vue")['default']
    'PageBanner': typeof import("../components/PageBanner.vue")['default']
    'Preloader': typeof import("../components/Preloader.vue")['default']
    'ProgressBar': typeof import("../components/ProgressBar.vue")['default']
    'ScrollTop': typeof import("../components/ScrollTop.vue")['default']
    'CountersCounter': typeof import("../components/counters/Counter.vue")['default']
    'FootersFooter': typeof import("../components/footers/Footer.vue")['default']
    'FootersFooter1': typeof import("../components/footers/Footer1.vue")['default']
    'FootersFooter2': typeof import("../components/footers/Footer2.vue")['default']
    'FootersFooter3': typeof import("../components/footers/Footer3.vue")['default']
    'FootersFooter4': typeof import("../components/footers/Footer4.vue")['default']
    'FootersFooter5': typeof import("../components/footers/Footer5.vue")['default']
    'FootersFooter6': typeof import("../components/footers/Footer6.vue")['default']
    'HeadersHeader': typeof import("../components/headers/Header.vue")['default']
    'HeadersHeader1': typeof import("../components/headers/Header1.vue")['default']
    'HeadersHeader2': typeof import("../components/headers/Header2.vue")['default']
    'HeadersHeader3': typeof import("../components/headers/Header3.vue")['default']
    'HeadersNav': typeof import("../components/headers/Nav.vue")['default']
    'HeadersSearch': typeof import("../components/headers/Search.vue")['default']
    'HeadersSidebar': typeof import("../components/headers/Sidebar.vue")['default']
    'SlidersGallery': typeof import("../components/sliders/Gallery.vue")['default']
    'SlidersHero5': typeof import("../components/sliders/Hero5.vue")['default']
    'SlidersProject': typeof import("../components/sliders/Project.vue")['default']
    'SlidersProject2': typeof import("../components/sliders/Project2.vue")['default']
    'SlidersTestimonial': typeof import("../components/sliders/Testimonial.vue")['default']
    'SlidersTestimonial2': typeof import("../components/sliders/Testimonial2.vue")['default']
    'SlidersTestimonial3': typeof import("../components/sliders/Testimonial3.vue")['default']
    'SlidersTestimonial4': typeof import("../components/sliders/Testimonial4.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyMfpPopup': typeof import("../components/MfpPopup.vue")['default']
    'LazyPageBanner': typeof import("../components/PageBanner.vue")['default']
    'LazyPreloader': typeof import("../components/Preloader.vue")['default']
    'LazyProgressBar': typeof import("../components/ProgressBar.vue")['default']
    'LazyScrollTop': typeof import("../components/ScrollTop.vue")['default']
    'LazyCountersCounter': typeof import("../components/counters/Counter.vue")['default']
    'LazyFootersFooter': typeof import("../components/footers/Footer.vue")['default']
    'LazyFootersFooter1': typeof import("../components/footers/Footer1.vue")['default']
    'LazyFootersFooter2': typeof import("../components/footers/Footer2.vue")['default']
    'LazyFootersFooter3': typeof import("../components/footers/Footer3.vue")['default']
    'LazyFootersFooter4': typeof import("../components/footers/Footer4.vue")['default']
    'LazyFootersFooter5': typeof import("../components/footers/Footer5.vue")['default']
    'LazyFootersFooter6': typeof import("../components/footers/Footer6.vue")['default']
    'LazyHeadersHeader': typeof import("../components/headers/Header.vue")['default']
    'LazyHeadersHeader1': typeof import("../components/headers/Header1.vue")['default']
    'LazyHeadersHeader2': typeof import("../components/headers/Header2.vue")['default']
    'LazyHeadersHeader3': typeof import("../components/headers/Header3.vue")['default']
    'LazyHeadersNav': typeof import("../components/headers/Nav.vue")['default']
    'LazyHeadersSearch': typeof import("../components/headers/Search.vue")['default']
    'LazyHeadersSidebar': typeof import("../components/headers/Sidebar.vue")['default']
    'LazySlidersGallery': typeof import("../components/sliders/Gallery.vue")['default']
    'LazySlidersHero5': typeof import("../components/sliders/Hero5.vue")['default']
    'LazySlidersProject': typeof import("../components/sliders/Project.vue")['default']
    'LazySlidersProject2': typeof import("../components/sliders/Project2.vue")['default']
    'LazySlidersTestimonial': typeof import("../components/sliders/Testimonial.vue")['default']
    'LazySlidersTestimonial2': typeof import("../components/sliders/Testimonial2.vue")['default']
    'LazySlidersTestimonial3': typeof import("../components/sliders/Testimonial3.vue")['default']
    'LazySlidersTestimonial4': typeof import("../components/sliders/Testimonial4.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const MfpPopup: typeof import("../components/MfpPopup.vue")['default']
export const PageBanner: typeof import("../components/PageBanner.vue")['default']
export const Preloader: typeof import("../components/Preloader.vue")['default']
export const ProgressBar: typeof import("../components/ProgressBar.vue")['default']
export const ScrollTop: typeof import("../components/ScrollTop.vue")['default']
export const CountersCounter: typeof import("../components/counters/Counter.vue")['default']
export const FootersFooter: typeof import("../components/footers/Footer.vue")['default']
export const FootersFooter1: typeof import("../components/footers/Footer1.vue")['default']
export const FootersFooter2: typeof import("../components/footers/Footer2.vue")['default']
export const FootersFooter3: typeof import("../components/footers/Footer3.vue")['default']
export const FootersFooter4: typeof import("../components/footers/Footer4.vue")['default']
export const FootersFooter5: typeof import("../components/footers/Footer5.vue")['default']
export const FootersFooter6: typeof import("../components/footers/Footer6.vue")['default']
export const HeadersHeader: typeof import("../components/headers/Header.vue")['default']
export const HeadersHeader1: typeof import("../components/headers/Header1.vue")['default']
export const HeadersHeader2: typeof import("../components/headers/Header2.vue")['default']
export const HeadersHeader3: typeof import("../components/headers/Header3.vue")['default']
export const HeadersNav: typeof import("../components/headers/Nav.vue")['default']
export const HeadersSearch: typeof import("../components/headers/Search.vue")['default']
export const HeadersSidebar: typeof import("../components/headers/Sidebar.vue")['default']
export const SlidersGallery: typeof import("../components/sliders/Gallery.vue")['default']
export const SlidersHero5: typeof import("../components/sliders/Hero5.vue")['default']
export const SlidersProject: typeof import("../components/sliders/Project.vue")['default']
export const SlidersProject2: typeof import("../components/sliders/Project2.vue")['default']
export const SlidersTestimonial: typeof import("../components/sliders/Testimonial.vue")['default']
export const SlidersTestimonial2: typeof import("../components/sliders/Testimonial2.vue")['default']
export const SlidersTestimonial3: typeof import("../components/sliders/Testimonial3.vue")['default']
export const SlidersTestimonial4: typeof import("../components/sliders/Testimonial4.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyMfpPopup: typeof import("../components/MfpPopup.vue")['default']
export const LazyPageBanner: typeof import("../components/PageBanner.vue")['default']
export const LazyPreloader: typeof import("../components/Preloader.vue")['default']
export const LazyProgressBar: typeof import("../components/ProgressBar.vue")['default']
export const LazyScrollTop: typeof import("../components/ScrollTop.vue")['default']
export const LazyCountersCounter: typeof import("../components/counters/Counter.vue")['default']
export const LazyFootersFooter: typeof import("../components/footers/Footer.vue")['default']
export const LazyFootersFooter1: typeof import("../components/footers/Footer1.vue")['default']
export const LazyFootersFooter2: typeof import("../components/footers/Footer2.vue")['default']
export const LazyFootersFooter3: typeof import("../components/footers/Footer3.vue")['default']
export const LazyFootersFooter4: typeof import("../components/footers/Footer4.vue")['default']
export const LazyFootersFooter5: typeof import("../components/footers/Footer5.vue")['default']
export const LazyFootersFooter6: typeof import("../components/footers/Footer6.vue")['default']
export const LazyHeadersHeader: typeof import("../components/headers/Header.vue")['default']
export const LazyHeadersHeader1: typeof import("../components/headers/Header1.vue")['default']
export const LazyHeadersHeader2: typeof import("../components/headers/Header2.vue")['default']
export const LazyHeadersHeader3: typeof import("../components/headers/Header3.vue")['default']
export const LazyHeadersNav: typeof import("../components/headers/Nav.vue")['default']
export const LazyHeadersSearch: typeof import("../components/headers/Search.vue")['default']
export const LazyHeadersSidebar: typeof import("../components/headers/Sidebar.vue")['default']
export const LazySlidersGallery: typeof import("../components/sliders/Gallery.vue")['default']
export const LazySlidersHero5: typeof import("../components/sliders/Hero5.vue")['default']
export const LazySlidersProject: typeof import("../components/sliders/Project.vue")['default']
export const LazySlidersProject2: typeof import("../components/sliders/Project2.vue")['default']
export const LazySlidersTestimonial: typeof import("../components/sliders/Testimonial.vue")['default']
export const LazySlidersTestimonial2: typeof import("../components/sliders/Testimonial2.vue")['default']
export const LazySlidersTestimonial3: typeof import("../components/sliders/Testimonial3.vue")['default']
export const LazySlidersTestimonial4: typeof import("../components/sliders/Testimonial4.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
